# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18EpgxSqeoZsxzx5OgsGNxIawtBKCRxVp

ans 1
"""

import plotly.graph_objects as go

import seaborn as sb
df = sb.load_dataset('titanic')

fig = go.Figure()
fig.add_trace(go.Scatter(x = df.age,y =df.fare,mode = 'markers'))

"""ANS = 2"""

import plotly.express as px

df = sb.load_dataset('tips')
fig = px.box(df, y="total_bill")
fig.show()

"""ANS = 3

"""

import plotly.express as px
df = sb.load_dataset('tips')
fig = px.histogram(df, x="total_bill", pattern_shape = "smoker" , color = "day")
fig.show()

"""ans = 4"""

from seaborn.utils import load_dataset

import plotly.express as px
df = load_dataset('iris')
fig = px.scatter_matrix(df,
    dimensions=["sepal_length", "sepal_width", "petal_length", "petal_width"],
    color="species")
fig.show()

"""ans = 5"""

# Depicts the variation in the data distribution

import plotly.express as px
df = load_dataset('tips')
fig = px.histogram(df, x="total_bill", y="tip", color="sex",
                   marginal="box", 
                   hover_data=df.columns)
fig.show()





